main/urls.py
from django.urls import path
from main import views
from .views import *

app_name="main"
urlpatterns = [
    path('',views.showmain, name="showmain"),
    path('show/',views.show_show, name= "show"),
    path('past/',views.show_past, name= "past"),
    path('present/',views.show_present, name= "present"),
    path('future/',views.show_future, name= "future"),
    path('<str:id>', views.detail, name="detail"),
    path('new/',views.new, name= "new"),
    path('create/',views.create, name= "create"),
    path('edit/<str:id>',views.edit, name= "edit"),
    path('update/<str:id>',views.update, name= "update"),
    path('delete/<str:id>',views.delete, name= "delete"),
    path('more/',views.more, name= "more"),
    path('<str:post_id>/create_comment', views.create_comment, name="create_comment"),
    path('<str:post_id>/edit_comment', views.edit_comment, name="edit_comment"),
    path('<str:post_id>/update_comment', views.update_comment, name="update_comment"),
    path('<str:post_id>/delete_comment', views.delete_comment, name="delete_comment"),
    path('like_toggle/<int:post_id>/', views.like_toggle, name="like_toggle"),
    path('dislike_toggle/<int:post_id>/', views.dislike_toggle, name="dislike_toggle"),
]

sns_project/sns_project/urls.py
from django.contrib import admin
from django.urls import path
from main import views as main
from main import views as show
from main import views as past
from main import views as present
from main import views as future


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',main.showmain),
    path('show/',show.show_show),
    path('past/',past.show_past),
    path('present/',present.show_present),
    path('future/',future.show_future)
]

sns_project/urls.py
from os import stat
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/',include('allauth.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('<int:id>/mypage', views.mypage, name="mypage"),
    path('<int:id>/follow',views.follow,name="follow"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    followings=models.ManyToManyField("self", related_name="followers", symmetrical=False)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

users/views.py
from django.shortcuts import get_object_or_404, render, redirect
from main.models import Post
from .models import User

# Create your views here.
def mypage(request, id):
    user = get_object_or_404(User, pk=id)
    context = {
        'user' : user,
        'posts' : Post.objects.filter(writer=user)
    }
    
    return render(request, 'users/mypage.html', context)


def follow(request,id):
    user=request.user
    followed_user=get_object_or_404(User,pk=id)
    is_follower=user.profile in followed_user.profile.followers.all()
    if is_follower:
        user.profile.followings.remove(followed_user.profile)
    else:
        user.profile.followings.add(followed_user.profile)
    return redirect('users:mypage', followed_user.id)

users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h1>
        {% if 'user' in user.username and user.username != 'user' %}
            {{ user.last_name }}{{ user.first_name }}
        {% else %}
            {{ user.username }}
        {% endif %}
        </h1>
        {% if request.user != user %}<!--다른 사람의 프로필에 들어온 경우에만 팔로우/언팔로우 버튼이보임-->
            {% if request.user.profile in user.profile.followers.all %}
                <a href="{%url 'users:follow' user.id %}"><button type="button" class="btn btn-outline-info">언팔로우</button></a>
            {% else %}
            <a href="{%url 'users:follow' user.id %}"><button type="button" class="btn btn-info">팔로우</button></a>
            {% endif %}
        {% endif %}
        <div class="container">
            <h3>팔로워{{user.profile.followers.count}}명</h3>
            {%for follower in user.profile.followers.all %}
                <a href="{% url 'users:mypage' follower.user.id %}">{{follower.user.username}}</a>
            {% endfor %}
            <h3>팔로잉{{user.profile.followings.count}}명</h3>
            {% for following in user.profile.followings.all %}
                <a href="{%url 'users:mypage' following.user.id%}">{{following.user.username}}</a>
            {% endfor %}
            </div>
        <div>
            {% for post in posts %}
                <a href="{%url 'main:detail' post.id%}">{{post.title}}</a><hr>
            {%endfor%}
        </div>
</div>
{% endblock %}