main/urls.py
from django.urls import path
from main import views
from .views import *

app_name="main"
urlpatterns = [
    path('',views.showmain, name="showmain"),
    path('show/',views.show_show, name= "show"),
    path('past/',views.show_past, name= "past"),
    path('present/',views.show_present, name= "present"),
    path('future/',views.show_future, name= "future"),
    path('<str:id>', views.detail, name="detail"),
    path('new/',views.new, name= "new"),
    path('create/',views.create, name= "create"),
    path('edit/<str:id>',views.edit, name= "edit"),
    path('update/<str:id>',views.update, name= "update"),
    path('delete/<str:id>',views.delete, name= "delete"),
    path('more/',views.more, name= "more"),
    path('<str:post_id>/create_comment', views.create_comment, name="create_comment"),
    path('<str:post_id>/edit_comment', views.edit_comment, name="edit_comment"),
    path('<str:post_id>/update_comment', views.update_comment, name="update_comment"),
    path('<str:post_id>/delete_comment', views.delete_comment, name="delete_comment"),
    path('like_toggle/<int:post_id>/', views.like_toggle, name="like_toggle"),
    path('dislike_toggle/<int:post_id>/', views.dislike_toggle, name="dislike_toggle"),
]

sns_project/sns_project/urls.py
from django.contrib import admin
from django.urls import path
from main import views as main
from main import views as show
from main import views as past
from main import views as present
from main import views as future


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',main.showmain),
    path('show/',show.show_show),
    path('past/',past.show_past),
    path('present/',present.show_present),
    path('future/',future.show_future)
]

sns_project/urls.py
from os import stat
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/',include('allauth.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('<int:id>/mypage', views.mypage, name="mypage"),
    path('<int:id>/follow',views.follow,name="follow"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to = "post/", blank=True, null=True)
    like_user_set = models.ManyToManyField(User, blank=True, related_name='likes_user_set',through='Like')
    dislike_user_set = models.ManyToManyField(User, blank=True, related_name='dislikes_user_set',through='Dislike')

    def __str__(self):
        return self.title

    @property
    def like_count(self):
        return self.like_user_set.count()

    @property
    def dislike_count(self):
        return self.dislike_user_set.count()

class Comment(models.Model):
	content = models.TextField()
	writer = models.ForeignKey(User, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together =(('user', 'post'))

class Dislike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (('user', 'post'))

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import HttpResponse
import json

# Create your views here.
def showmain(request):
    posts = Post.objects.all()
    return render(request, 'main/mainpage.html', {'posts':posts})

def show_show(request):
    return render(request, 'main/show.html')

def show_past(request):
    return render(request, 'main/past.html')

def show_present(request):
    return render(request, 'main/present.html')

def show_future(request):
    return render(request, 'main/future.html')

def detail(request, id):
    post = get_object_or_404(Post, pk = id)
    all_comments = post.comments.all().order_by('-created_at')
    return render(request, 'main/detail.html',{'post':post, 'comments': all_comments})

def new(request):
    return render(request, 'main/new.html')

def more(request):
    posts = Post.objects.all()
    return render(request, 'main/more.html', {'posts':posts})

def create(request):
    new_post = Post()
    new_post.title = request.POST['title']
    new_post.writer = request.user
    new_post.pub_date = timezone.now() 
    new_post.body = request.POST['body']
    new_post.image = request.FILES.get('image')
    new_post.save()
    return redirect('main:detail', new_post.id)

def edit(request, id):
    edit_post = Post.objects.get(id = id)
    return render(request, 'main/edit.html', {'post': edit_post})

def update(request, id):
    update_post = get_object_or_404(Post, id = id)
    update_post.title = request.POST['title']
    update_post.writer = request.user
    update_post.pub_date = timezone.now() 
    update_post.body = request.POST['body']
    update_post.image = request.FILES.get('image')
    update_post.save()
    return redirect('main:detail', update_post.id)

def delete(request, id):
    delete_post = Post.objects.get(id=id)
    delete_post.delete()
    return redirect('main:more')

def create_comment(request, post_id):
    new_comment = Comment()
    new_comment.writer = request.user
    new_comment.content = request.POST['content']
    new_comment.post = get_object_or_404(Post, pk = post_id)
    new_comment.save()
    return redirect('main:detail', post_id)

def edit_comment(request, post_id):
    edit_comment = Comment.objects.get(id = post_id)
    return render(request, 'main/edit_comment.html', {'comment': edit_comment})

def update_comment(request, post_id):
    update_comment = get_object_or_404(Comment, id = post_id)
    update_comment.writer = request.user
    update_comment.content = request.POST['content']
    update_comment.save()
    return redirect('main:detail', update_comment.post_id)

def delete_comment(request, post_id):
    delete_comment = Comment.objects.get(id=post_id)
    delete_comment.delete()
    return redirect('main:more')

@login_required
@require_POST

def like_toggle(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_like, post_like_created = Like.objects.get_or_create(user=request.user, post=post)

    if not post_like_created:
        post_like.delete()
        result = "like_cancel"
    else:
        result = "like"
    
    context = {
        "like_count":post.like_count,
        "result":result
    }

    return HttpResponse(json.dumps(context), content_type="application/json")

def dislike_toggle(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_dislike, post_dislike_created = Dislike.objects.get_or_create(user=request.user, post=post)

    if not post_dislike_created:
        post_dislike.delete()
        result = "dislike_cancel"
    else:
        result = "dislike"
    
    context = {
        "dislike_count":post.dislike_count,
        "result":result
    }

    return HttpResponse(json.dumps(context), content_type="application/json")

main/templates/main/detail.html
<h1>{{post.title}}</h1>
<br>
{% if post.writer %}
    {% if 'user' in post.writer.username and post.writer.username != 'user' %}
        <br>작성자: <a href="{% url 'users:mypage' post.writer.id %}">{{post.writer.last_name}} {{post.writer.first_name}}</a>
    {% else %}
        <br>작성자: <a href="{% url 'users:mypage' post.writer.id %}">{{post.writer}}</a>
    {% endif %}
{% else %}
    <br>작성자: Who Are You? MoFu
{% endif %}
<br>날짜: {{post.pub_date}}
<br>
{% if post.image %}
    <p><img src="{{post.image.url}}" alt="사진"></p>
{% endif %}
<br><p>{{post.body}}</p>
<br><a href="{% url 'main:more' %}">글 목록으로 돌아가기</a>
<br><a href="{% url 'main:edit' post.id %}">수정하기</a>
<br><a href="{% url 'main:delete' post.id %}">삭제하기</a>
<span href="#" class="like" name="{{post.name}}" value="Like">
    {% if user in post.like_user_set.all %}
    <div class="alt-service-icon">
        <i class="fas fa-thumbs-up" id="like-icon" style="color: red;"></i>
    </div>
    {% else %}
    <div class="alt-service-icon">
        <i class="far fa-thumbs-up" id="like-icon" style="color:red;"></i>
    </div>
    {% endif %}
    <span id="count-{{post.id}}_like" class="alt-services-title font-alt">
        좋아요
        {% if post.like_count == 0 %}
        0개
        {% else %}
        {{post.like_count}}개
        {% endif %}
    </span>
</span>

<span href="#" class="dislike" name="{{post.name}}" value="Dislike">
    {% if user in post.dislike_user_set.all %}
    <div class="alt-service-icon">
        <i class="fas fa-thumbs-down" id="dislike-icon" style="color: red;"></i>
    </div>
    {% else %}
    <div class="alt-service-icon">
        <i class="far fa-thumbs-down" id="dislike-icon" style="color:red;"></i>
    </div>
    {% endif %}
    <span id="count-{{post.id}}_dislike" class="alt-services-title font-alt">
        싫어요
        {% if post.dislike_count == 0 %}
        0개
        {% else %}
        {{post.dislike_count}}개
        {% endif %}
    </span>
</span>
<br><br><br><br><br>
<h3>[댓글]</h3>
<div>
    {% for comment in comments %}
    <div>
        <br>
        작성자: {{comment.writer}}<br>
        {{comment.content}}
        <br><a href="{% url 'main:edit_comment' comment.id %}">수정하기</a>
        <br><a href="{% url 'main:delete_comment' comment.id %}">삭제하기</a>
    </div>
    {% endfor %}
</div>
<br><br><br><br><br>
<div>
	<form action="{%url 'main:create_comment' post.id%}" method="POST">
		{%csrf_token%}
		<textarea name="content" placeholder="댓글내용입력"></textarea>
		<input type="submit" value="확인">
	</form>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

<script>
    $(".like").click(function(){
        var pk = $(this).attr('name')
        $.ajax({
            url : "{% url 'main:like_toggle' post.pk %}",
            data : {'pk':pk,'csrfmiddlewaretoken': '{{ csrf_token }}'},
            type:"POST",
            dataType:"json",
            
            success: function(response){

                if (response.like_count==null){
                    alert("로그인이 필요합니다.");
                    window.location.replace('/accounts/login/')
                }
                else{
                    if (response.result == "like"){
                        $('#like-icon').removeClass();
                        $('#like-icon').addClass('fas fa-thumbs-up');
                    }
                    else{
                        $('#like-icon').removeClass();
                        $('#like-icon').addClass('far fa-thumbs-up');
                    }

                    $('#count-{{ post.id }}_like').html('좋아요 '+response.like_count+'개');
                }
            },

            error: function(request, status, error){
                alert("로그인이 필요합니다.")
	            alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error); 
        	},
         });
    })


    $(".dislike").click(function(){
        var pk = $(this).attr('name')
        $.ajax({
            url : "{% url 'main:dislike_toggle' post.pk %}",
            data : {'pk':pk,'csrfmiddlewaretoken': '{{ csrf_token }}'},
            type:"POST",
            dataType:"json",
            
            success: function(response){

                if (response.dislike_count==null){
                    alert("로그인이 필요합니다.");
                    window.location.replace('/accounts/login/')
                }
                else{
                    if (response.result == "dislike"){
                        $('#dislike-icon').removeClass();
                        $('#dislike-icon').addClass('fas fa-thumbs-down');
                    }
                    else{
                        $('#dislike-icon').removeClass();
                        $('#dislike-icon').addClass('far fa-thumbs-down');
                    }

                    $('#count-{{ post.id }}_dislike').html('싫어요 '+response.dislike_count+'개');
                }
            },

            error: function(request, status, error){
                alert("로그인이 필요합니다.")
	            alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error); 
        	},
         });
    })
 </script>
 <script
    src="https://kit.fontawesome.com/6478f529f2.js"
    crossorigin="anonymous"
></script>

main/templates/main/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form action = "{% url 'main:update' post.id %}" method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>제목: <input type="text" name="title" value="{{post.title}}"></p>
    <p>사진: <input type="file" name="image" {{post.image}}></p>
    <p>내용: <input type="text" name="body" id="" cols="30" rows="10" {{post.body}}></p>
    <button type="submit">제출</button>
</form>

{% endblock %}

main/templates/main/edit_comment.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div>
	<form action="{%url 'main:update_comment' comment.id %}" method="POST">
		{%csrf_token%}
		<textarea name="content" placeholder="댓글내용입력" value="{{comment.content}}"></textarea>
		<input type="submit" value="확인">
	</form>
</div>

{% endblock %}

main/templates/main/new.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}
<form action = "{% url 'main:create' %}" method = "post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>제목: <input type="text" name="title"></p>
    <p>사진: <input type="file" name="image"></p>
    <p>내용: <input type="text" name="body" id="" cols="30" rows="10"></p>
    <button type="submit">제출</button>
</form>
{% else %}
<h3>로그인 후 이용 가능</h3>
<a class="nav-link" href="{% url 'account_login' %}">OOO LOGIN OOO</a>
<a class="nav-link" href="{% url 'account_signup' %}">OOO SIGNUP OOO</a>
{% endif %}

{% endblock %}

main/templates/main/show.html
<h1>5/3일 완료!</h1>