main/urls.py
from django.urls import path
from main import views
from .views import *

app_name="main"
urlpatterns = [
    path('',views.showmain, name="showmain"),
    path('show/',views.show_show, name= "show"),
    path('past/',views.show_past, name= "past"),
    path('present/',views.show_present, name= "present"),
    path('future/',views.show_future, name= "future"),
    path('<str:id>', views.detail, name="detail"),
    path('new/',views.new, name= "new"),
    path('create/',views.create, name= "create"),
    path('edit/<str:id>',views.edit, name= "edit"),
    path('update/<str:id>',views.update, name= "update"),
    path('delete/<str:id>',views.delete, name= "delete"),
    path('more/',views.more, name= "more"),
    path('<str:post_id>/create_comment', views.create_comment, name="create_comment"),
    path('<str:post_id>/edit_comment', views.edit_comment, name="edit_comment"),
    path('<str:post_id>/update_comment', views.update_comment, name="update_comment"),
    path('<str:post_id>/delete_comment', views.delete_comment, name="delete_comment"),
    path('like_toggle/<int:post_id>/', views.like_toggle, name="like_toggle"),
    path('dislike_toggle/<int:post_id>/', views.dislike_toggle, name="dislike_toggle"),
]

sns_project/sns_project/urls.py
from django.contrib import admin
from django.urls import path
from main import views as main
from main import views as show
from main import views as past
from main import views as present
from main import views as future


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',main.showmain),
    path('show/',show.show_show),
    path('past/',past.show_past),
    path('present/',present.show_present),
    path('future/',future.show_future)
]

sns_project/urls.py
from os import stat
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/',include('allauth.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('<int:id>/mypage', views.mypage, name="mypage"),
    path('<int:id>/follow',views.follow,name="follow"),
]

sns_project/templates/shared/_navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        
        .nav-link{
          border: 1px solid black;
          background-color: rgb(253, 157, 68);
          font-weight: 300;
        }
        .navbar-nav{
          display: flex;
          justify-content: space-between;
        }
        .nav-link:hover{
          font-weight: 600;
          background-color: rgb(253, 122, 0);
        }
        .navbar{
          height: 55px;
          background-color: orange;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url 'main:showmain' %}">OOO Main OOO</a>
              <a class="nav-link" href="{% url 'main:past' %}">OOO Past OOO</a>
              <a class="nav-link" href="{% url 'main:present' %}">OOO Present OOO</a>
              <a class="nav-link" href="{% url 'main:future' %}">OOO Future OOO</a>
              {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'account_logout' %}">OOO LOGOUT OOO</a>
              <a class="nav-link" href="{% url 'users:mypage' request.user.id %}">OOO MYPAGE OOO</a>
              {% else %}
              <a class="nav-link" href="{% url 'account_login' %}">OOO LOGIN OOO</a>
              <a class="nav-link" href="{% url 'account_signup' %}">OOO SIGNUP OOO</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>

</body>
</html>